# Generated by Django 4.2.5 on 2023-09-14 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='snippet',
            table='snippets',
        ),
    ]
